=== govuk-one-login/account-components/solutions/config/schema/config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.manage.account.gov.uk/app-config/v1.0.0.json",
  "title": "App Config Schema",
  "description": "A schema to validate app config",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "client_registry": {
      "description": "Authorised AMC clients (Relying Parties) properties",
      "type": "array",
      "items": {
        "$ref": "#/$defs/clientEntry"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "jti_nonce_ttl_in_seconds": {
      "description": "Time-to-live in seconds for JTI nonce",
      "type": "integer",
      "minimum": 1
    },
    "auth_code_ttl": {
      "description": "Time-to-live in seconds for auth code",
      "type": "integer",
      "minimum": 1
    },
    "jwks_cache_max_age": {
      "description": "Max Age (ms) to cache JWKS",
      "type": "integer",
      "minimum": 1000
    },
    "jwks_http_timeout": {
      "description": "JWKS fetch HTTP Timeout (ms)",
      "type": "integer",
      "minimum": 1000
    },
    "journey_outcome_ttl": {
      "description": "Time-to-live in seconds for journey outcome",
      "type": "integer",
      "minimum": 1
    },
    "access_token_max_age": {
      "description": "Maximum age of access token",
      "type": "integer",
      "minimum": 1
    },
    "max_number_of_passkeys": {
      "description": "The maximum number of passkeys a user can have",
      "type": "integer"
    }
  },
  "required": [
    "client_registry",
    "jti_nonce_ttl_in_seconds",
    "auth_code_ttl",
    "jwks_cache_max_age",
    "jwks_http_timeout",
    "access_token_max_age",
    "journey_outcome_ttl",
    "max_number_of_passkeys"
  ],
  "$defs": {
    "analytics": {
      "type": "object",
      "properties": {
        "contentId": { "type": "string" },
        "isPageDataSensitive": { "type": "boolean" },
        "taxonomyLevel1": { "type": "string" },
        "taxonomyLevel2": { "type": "string" },
        "taxonomyLevel3": { "type": "string" },
        "dynamic": { "type": "boolean" },
        "isSelectContentTrackingEnabled": { "type": "boolean" }
      },
      "additionalProperties": false
    },
    "clientEntry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "client_id": {
          "description": "Unique client_id issued to an AMC client",
          "type": "string",
          "pattern": "^[A-Za-z0-9]+$"
        },
        "scope": {
          "description": "String containing a space-separated list of scope values that the client can use",
          "type": "string",
          "minLength": 1,
          "maxLength": 255,
          "pattern": "^[a-z]+(?:-?[a-z]+)*(?:\\s[a-z]+(?:-?[a-z]+)*)*$"
        },
        "redirect_uris": {
          "type": "array",
          "description": "Array of redirection URI strings for use in redirect-based flows",
          "items": {
            "type": "string",
            "description": "A Redirect URI, also known as a Reply URL, specifies the URL where users are sent after the user has completed their AMC journey",
            "format": "uri",
            "pattern": "^(https|http)://(www\\.)?((localhost(:[0-9]+)?)|[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b)([-a-zA-Z0-9()@:%_+.~#?&/=]*)$",
            "minLength": 1,
            "maxLength": 255
          },
          "uniqueItems": true
        },
        "client_name": {
          "description": "Human-readable string name of the client that could be presented to the end-user",
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        },
        "jwks_uri": {
          "description": "URL string referencing the client's JSON Web Key (JWK) Set",
          "type": "string",
          "format": "uri",
          "pattern": "^(https|http)://(www\\.)?((localhost(:[0-9]+)?)|[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b)([-a-zA-Z0-9()@:%_+.~#?&/=]*)$",
          "minLength": 1,
          "maxLength": 255
        },
        "jwks_uri_from_container": {
          "description": "URL string referencing the client's JSON Web Key (JWK) Set if the caller is in a container (only needed for local development)",
          "type": "string",
          "format": "uri",
          "pattern": "^(https|http)://(www\\.)?((localhost(:[0-9]+)?)|[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b)([-a-zA-Z0-9()@:%_+.~#?&/=]*)$",
          "minLength": 1,
          "maxLength": 255
        },
        "consider_user_logged_in": {
          "description": "Boolean flag to determine if the user should be considered logged in",
          "type": "boolean"
        },
        "homepage_url": {
          "description": "Optional URL for the homepage",
          "type": "string",
          "format": "uri",
          "pattern": "^(https|http)://(www\\.)?((localhost(:[0-9]+)?)|[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b)([-a-zA-Z0-9()@:%_+.~#?&/=]*)$",
          "minLength": 1,
          "maxLength": 255
        },
        "analytics": {
          "type": "object",
          "properties": {
            "passkeyCreate": { "$ref": "#/$defs/analytics" },
            "passkeyCreateError": { "$ref": "#/$defs/analytics" }
          },
          "additionalProperties": false
        },
        "journey_types_by_scope": {
          "type": "object",
          "additionalProperties": { "type": "string" }
        }
      },
      "required": [
        "client_id",
        "scope",
        "redirect_uris",
        "client_name",
        "jwks_uri",
        "consider_user_logged_in"
      ]
    }
  }
}

=== govuk-one-login/account-components/solutions/config/staging-config.json
{
  "client_registry": [
    {
      "client_id": "auth",
      "scope": "account-delete passkey-create",
      "redirect_uris": [
        "https://signin.staging.account.gov.uk/create-passkey-callback"
      ],
      "client_name": "Auth",
      "jwks_uri": "https://z02rnzbqw8.execute-api.eu-west-2.amazonaws.com/staging/.well-known/amc-jwks.json",
      "consider_user_logged_in": false,
      "journey_types_by_scope": {
        "passkey-create": "SIGN_IN",
        "account-delete": "SIGN_IN"
      }
    },
    {
      "client_id": "home",
      "scope": "passkey-create",
      "redirect_uris": ["https://home.staging.account.gov.uk/amc/callback"],
      "client_name": "Home",
      "jwks_uri": "https://home.staging.account.gov.uk/.well-known/jwks.json",
      "consider_user_logged_in": true,
      "homepage_url": "https://home.staging.account.gov.uk/your-services",
      "journey_types_by_scope": {
        "passkey-create": "ACCOUNT_MANAGEMENT"
      }
    }
  ],
  "jti_nonce_ttl_in_seconds": 7200,
  "auth_code_ttl": 300,
  "jwks_cache_max_age": 900000,
  "jwks_http_timeout": 2500,
  "access_token_max_age": 300,
  "journey_outcome_ttl": 360,
  "max_number_of_passkeys": 5
}

=== govuk-one-login/account-components/solutions/config/local-config.json
{
  "client_registry": [
    {
      "client_id": "auth",
      "scope": "testing-journey account-delete passkey-create",
      "redirect_uris": ["http://localhost:6003/auth/callback"],
      "client_name": "Auth",
      "jwks_uri": "http://localhost:6003/auth/.well-known/jwks.json",
      "jwks_uri_from_container": "http://host.docker.internal:6003/auth/.well-known/jwks.json",
      "consider_user_logged_in": false,
      "journey_types_by_scope": {
        "passkey-create": "SIGN_IN",
        "account-delete": "SIGN_IN"
      }
    },
    {
      "client_id": "home",
      "scope": "testing-journey passkey-create",
      "redirect_uris": ["http://localhost:6003/home/callback"],
      "client_name": "Home",
      "jwks_uri": "http://localhost:6003/home/.well-known/jwks.json",
      "jwks_uri_from_container": "http://host.docker.internal:6003/home/.well-known/jwks.json",
      "consider_user_logged_in": true,
      "homepage_url": "https://home.dev.account.gov.uk/your-services",
      "journey_types_by_scope": {
        "passkey-create": "ACCOUNT_MANAGEMENT"
      }
    }
  ],
  "jti_nonce_ttl_in_seconds": 7200,
  "auth_code_ttl": 300,
  "jwks_cache_max_age": 60000,
  "jwks_http_timeout": 2500,
  "access_token_max_age": 300,
  "journey_outcome_ttl": 360,
  "max_number_of_passkeys": 5
}

=== govuk-one-login/account-components/solutions/config/build-config.json
{
  "client_registry": [
    {
      "client_id": "auth",
      "scope": "testing-journey account-delete passkey-create",
      "redirect_uris": [
        "https://stubs.manage.build.account.gov.uk/auth/callback"
      ],
      "client_name": "Auth",
      "jwks_uri": "https://stubs.manage.build.account.gov.uk/auth/.well-known/jwks.json",
      "consider_user_logged_in": false,
      "journey_types_by_scope": {
        "passkey-create": "SIGN_IN",
        "account-delete": "SIGN_IN"
      }
    },
    {
      "client_id": "home",
      "scope": "testing-journey passkey-create",
      "redirect_uris": [
        "https://stubs.manage.build.account.gov.uk/home/callback"
      ],
      "client_name": "Home",
      "jwks_uri": "https://stubs.manage.build.account.gov.uk/home/.well-known/jwks.json",
      "consider_user_logged_in": true,
      "homepage_url": "https://home.build.account.gov.uk/your-services",
      "journey_types_by_scope": {
        "passkey-create": "ACCOUNT_MANAGEMENT"
      }
    }
  ],
  "jti_nonce_ttl_in_seconds": 7200,
  "auth_code_ttl": 300,
  "jwks_cache_max_age": 900000,
  "jwks_http_timeout": 2500,
  "access_token_max_age": 300,
  "journey_outcome_ttl": 360,
  "max_number_of_passkeys": 5
}

=== govuk-one-login/account-components/solutions/config/integration-config.json
{
  "client_registry": [
    {
      "client_id": "auth",
      "scope": "account-delete passkey-create",
      "redirect_uris": [
        "https://signin.integration.account.gov.uk/create-passkey-callback"
      ],
      "client_name": "Auth",
      "jwks_uri": "https://db10ia9pr6.execute-api.eu-west-2.amazonaws.com/integration/.well-known/amc-jwks.json",
      "consider_user_logged_in": false,
      "journey_types_by_scope": {
        "passkey-create": "SIGN_IN",
        "account-delete": "SIGN_IN"
      }
    },
    {
      "client_id": "home",
      "scope": "passkey-create",
      "redirect_uris": [
        "https://home.integration.account.gov.uk/amc/callback?scope=passkey-create"
      ],
      "client_name": "Home",
      "jwks_uri": "https://home.integration.account.gov.uk/.well-known/jwks.json",
      "consider_user_logged_in": true,
      "homepage_url": "https://home.integration.account.gov.uk/your-services",
      "journey_types_by_scope": {
        "passkey-create": "ACCOUNT_MANAGEMENT"
      }
    }
  ],
  "jti_nonce_ttl_in_seconds": 7200,
  "auth_code_ttl": 300,
  "jwks_cache_max_age": 900000,
  "jwks_http_timeout": 2500,
  "access_token_max_age": 300,
  "journey_outcome_ttl": 360,
  "max_number_of_passkeys": 5
}

=== govuk-one-login/account-components/solutions/config/production-config.json
{
  "client_registry": [
    {
      "client_id": "auth",
      "scope": "account-delete passkey-create",
      "redirect_uris": [
        "https://signin.account.gov.uk/create-passkey-callback"
      ],
      "client_name": "Auth",
      "jwks_uri": "https://86n9innl95.execute-api.eu-west-2.amazonaws.com/production/.well-known/amc-jwks.json",
      "consider_user_logged_in": false,
      "journey_types_by_scope": {
        "passkey-create": "SIGN_IN",
        "account-delete": "SIGN_IN"
      }
    },
    {
      "client_id": "home",
      "scope": "passkey-create",
      "redirect_uris": [
        "https://home.account.gov.uk/amc/callback?scope=passkey-create"
      ],
      "client_name": "Home",
      "jwks_uri": "https://home.account.gov.uk/.well-known/jwks.json",
      "consider_user_logged_in": true,
      "homepage_url": "https://home.account.gov.uk/your-services",
      "journey_types_by_scope": {
        "passkey-create": "ACCOUNT_MANAGEMENT"
      }
    }
  ],
  "jti_nonce_ttl_in_seconds": 7200,
  "auth_code_ttl": 300,
  "jwks_cache_max_age": 900000,
  "jwks_http_timeout": 2500,
  "access_token_max_age": 300,
  "journey_outcome_ttl": 360,
  "max_number_of_passkeys": 5
}
